name: 기본 템플릿
description: 기능 추가, 버그 수정 등의 PR을 생성할 때 작성해주세요!
title: "[PR] "

body:
  - type: input
    id: summary
    attributes:
      label: 작업 개요
      description: 이 PR에서 무엇을 작업했는지 간단히 적어주세요!
      placeholder: "예: 음악 드랍 기능 추가"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 작업 상세 내용
      description: 기능 구현, 수정 사항 등을 구체적으로 적어주세요!
      placeholder: |
        - 음악 드랍 UI 구현
        - 지도 마커 표시
        - 좌표 유효성 검사 추가
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: 해당 되는 내용을 체크해주세요!
      options:
        - label: "관련 이슈와 연결 (`Closes #이슈번호`)"
        - label: 기능 구현 또는 수정 완료
        - label: 테스트 완료
        - label: 코드 리뷰를 위한 설명

  - type: textarea
    id: issues
    attributes:
      label: 관련 이슈
      description: 관련된 이슈가 있다면 적어주세요!
      placeholder: "Closes #"

  - type: textarea
    id: screenshot
    attributes:
      label: 스크린샷 (자유)
      description: UI 변경이 있을 경우 스크린샷을 첨부해주세요!
      placeholder: 스크린샷을 올려주세요!
    validations:
      required: false

  - type: textarea
    id: note
    attributes:
      label: 참고사항
      description: 추가로 공유하고 싶은 참고사항이 있다면 적어주세요!
    validations:
      required: false