export const musicData = [
    {"musicTitle": "FAMOUS", "singer": "ALLDAY PROJECT"},
    {"musicTitle": "Golden", "singer": "HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast"},
    {"musicTitle": "Dirty Work", "singer": "aespa"},
    {"musicTitle": "Drowning", "singer": "WOODZ"},
    {"musicTitle": "뛰어(JUMP)", "singer": "BLACKPINK"},
    {"musicTitle": "너에게 닿기를", "singer": "10CM"},
    {"musicTitle": "UP (KARINA Solo)", "singer": "aespa"},
    {"musicTitle": "HANDS UP", "singer": "MEOVV"},
    {"musicTitle": "APT.", "singer": "로제 (ROSÉ), Bruno Mars"},
    {"musicTitle": "Welcome to the Show", "singer": "DAY6"},
    {"musicTitle": "LIKE YOU BETTER", "singer": "프로미스나인"},
    {"musicTitle": "REBEL HEART", "singer": "IVE"},
    {"musicTitle": "오늘만 I LOVE YOU", "singer": "BOYNEXTDOOR"},
    {"musicTitle": "빌려온 고양이", "singer": "ILLIT"},
    {"musicTitle": "한 페이지가 될 수 있게", "singer": "DAY6"},
    {"musicTitle": "소나기", "singer": "ECLIPSE"},
    {"musicTitle": "Supernova", "singer": "aespa"},
    {"musicTitle": "Magnetic", "singer": "ILLIT"},
    {"musicTitle": "Seven", "singer": "정국 (Jungkook) feat. Latto"},
    {"musicTitle": "I AM", "singer": "IVE"},
    {"musicTitle": "Hype Boy", "singer": "NewJeans"},
    {"musicTitle": "How Sweet", "singer": "NewJeans"},
    {"musicTitle": "Die With A Smile", "singer": "Lady Gaga, Bruno Mars"},
    {"musicTitle": "TAKE ME", "singer": "G-DRAGON"},
    {"musicTitle": "WICKED", "singer": "ALLDAY PROJECT"},
    {"musicTitle": "눈물참기", "singer": "QWER"},
    {"musicTitle": "TOO BAD", "singer": "G-DRAGON feat. Anderson .Paak"},
    {"musicTitle": "MY LOVE(2025)", "singer": "이예은, 아샤트리, 전건호"},
    {"musicTitle": "STYLE", "singer": "Hearts2Hearts"},
    {"musicTitle": "LOVE WINS ALL", "singer": "아이유"},
    {"musicTitle": "다정히 내 이름을 부르면", "singer": "경서예지, 전건호"},
    {"musicTitle": "봄날", "singer": "방탄소년단"},
    {"musicTitle": "헤어지자 말해요", "singer": "박재정"},
    {"musicTitle": "모래 알갱이", "singer": "임영웅"},
    {"musicTitle": "Ditto", "singer": "NewJeans"},
    {"musicTitle": "사랑은 늘 도망가", "singer": "임영웅"},
    {"musicTitle": "Super Shy", "singer": "NewJeans"},
    {"musicTitle": "꽃", "singer": "지수 (JISOO)"},
    {"musicTitle": "Still With You", "singer": "정국 (Jungkook)"},
    {"musicTitle": "Smoke", "singer": "다이나믹듀오, 릴러말즈"},
    {"musicTitle": "LOVE DIVE", "singer": "IVE"},
    {"musicTitle": "Antifreeze", "singer": "AKMU (악뮤)"},
    {"musicTitle": "ASAP", "singer": "STAYC"},
    {"musicTitle": "Queencard", "singer": "아이들"},
    {"musicTitle": "밤양갱", "singer": "비비"},
    {"musicTitle": "사건의 지평선", "singer": "윤하"},
    {"musicTitle": "Attention", "singer": "NewJeans"},
    {"musicTitle": "OMG", "singer": "NewJeans"},
    {"musicTitle": "UNFORGIVEN", "singer": "LE SSERAFIM"},
    {"musicTitle": "Eve, Psyche & The Bluebeard’s wife", "singer": "LE SSERAFIM"},
    {"musicTitle": "Cupid", "singer": "FIFTY FIFTY"},
    {"musicTitle": "Spicy", "singer": "aespa"},
    {"musicTitle": "Drama", "singer": "aespa"},
    {"musicTitle": "Shut Down", "singer": "BLACKPINK"},
    {"musicTitle": "Pink Venom", "singer": "BLACKPINK"},
    {"musicTitle": "Forever", "singer": "aespa"},
    {"musicTitle": "Illusion", "singer": "aespa"},
    {"musicTitle": "I Don’t Think That I Like Her", "singer": "Charlie Puth"},
    {"musicTitle": "As It Was", "singer": "Harry Styles"},
    {"musicTitle": "Levitating", "singer": "Dua Lipa"},
    {"musicTitle": "Kill Bill", "singer": "SZA"},
    {"musicTitle": "Paint The Town Red", "singer": "Doja Cat"},
    {"musicTitle": "Flowers", "singer": "Miley Cyrus"},
    {"musicTitle": "abcdefu", "singer": "GAYLE"},
    {"musicTitle": "good 4 u", "singer": "Olivia Rodrigo"},
    {"musicTitle": "drivers license", "singer": "Olivia Rodrigo"},
    {"musicTitle": "MONTERO", "singer": "Lil Nas X"},
    {"musicTitle": "Industry Baby", "singer": "Lil Nas X, Jack Harlow"},
    {"musicTitle": "Peaches", "singer": "Justin Bieber"},
    {"musicTitle": "Ghost", "singer": "Justin Bieber"},
    {"musicTitle": "Easy On Me", "singer": "Adele"},
    {"musicTitle": "Shivers", "singer": "Ed Sheeran"},
    {"musicTitle": "Bad Habits", "singer": "Ed Sheeran"},
    {"musicTitle": "Blinding Lights", "singer": "The Weeknd"},
    {"musicTitle": "Save Your Tears", "singer": "The Weeknd"},
    {"musicTitle": "Take My Breath", "singer": "The Weeknd"},
    {"musicTitle": "Anti-Hero", "singer": "Taylor Swift"},
    {"musicTitle": "Cruel Summer", "singer": "Taylor Swift"},
    {"musicTitle": "Lover", "singer": "Taylor Swift"},
    {"musicTitle": "The Feels", "singer": "TWICE"},
    {"musicTitle": "Set Me Free", "singer": "TWICE"},
    {"musicTitle": "Butter", "singer": "BTS"},
    {"musicTitle": "Dynamite", "singer": "BTS"},
    {"musicTitle": "Permission to Dance", "singer": "BTS"},
    {"musicTitle": "Yet to Come", "singer": "BTS"},
    {"musicTitle": "LALISA", "singer": "LISA"},
    {"musicTitle": "MONEY", "singer": "LISA"},
    {"musicTitle": "Nxde", "singer": "아이들"},
    {"musicTitle": "TOMBOY", "singer": "아이들"},
    {"musicTitle": "ELEVEN", "singer": "IVE"},
    {"musicTitle": "After LIKE", "singer": "IVE"},
    {"musicTitle": "Strawberry Moon", "singer": "아이유"},
    {"musicTitle": "Celebrity", "singer": "아이유"},
    {"musicTitle": "에잇 (Eight)", "singer": "아이유 feat. SUGA"},
    {"musicTitle": "Blueming", "singer": "아이유"},
    {"musicTitle": "밤편지", "singer": "아이유"},
    {"musicTitle": "사계", "singer": "태연"},
    {"musicTitle": "그대라는 시", "singer": "태연"}
  ]
  