export const musicData = [
    {"musicTitle": "FAMOUS", "singer": "ALLDAY PROJECT", "imgUrl": ""},
    {"musicTitle": "Golden", "singer": "HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast", "imgUrl": ""},
    {"musicTitle": "Dirty Work", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "Drowning", "singer": "WOODZ", "imgUrl": ""},
    {"musicTitle": "뛰어(JUMP)", "singer": "BLACKPINK", "imgUrl": ""},
    {"musicTitle": "너에게 닿기를", "singer": "10CM", "imgUrl": ""},
    {"musicTitle": "UP (KARINA Solo)", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "HANDS UP", "singer": "MEOVV", "imgUrl": ""},
    {"musicTitle": "APT.", "singer": "로제 (ROSÉ), Bruno Mars", "imgUrl": ""},
    {"musicTitle": "Welcome to the Show", "singer": "DAY6", "imgUrl": ""},
    {"musicTitle": "LIKE YOU BETTER", "singer": "프로미스나인", "imgUrl": ""},
    {"musicTitle": "REBEL HEART", "singer": "IVE", "imgUrl": ""},
    {"musicTitle": "오늘만 I LOVE YOU", "singer": "BOYNEXTDOOR", "imgUrl": ""},
    {"musicTitle": "빌려온 고양이", "singer": "ILLIT", "imgUrl": ""},
    {"musicTitle": "한 페이지가 될 수 있게", "singer": "DAY6", "imgUrl": ""},
    {"musicTitle": "소나기", "singer": "ECLIPSE", "imgUrl": ""},
    {"musicTitle": "Supernova", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "Magnetic", "singer": "ILLIT", "imgUrl": ""},
    {"musicTitle": "Seven", "singer": "정국 (Jungkook) feat. Latto", "imgUrl": ""},
    {"musicTitle": "I AM", "singer": "IVE", "imgUrl": ""},
    {"musicTitle": "Hype Boy", "singer": "NewJeans", "imgUrl": ""},
    {"musicTitle": "How Sweet", "singer": "NewJeans", "imgUrl": ""},
    {"musicTitle": "Die With A Smile", "singer": "Lady Gaga, Bruno Mars", "imgUrl": ""},
    {"musicTitle": "TAKE ME", "singer": "G-DRAGON", "imgUrl": ""},
    {"musicTitle": "WICKED", "singer": "ALLDAY PROJECT", "imgUrl": ""},
    {"musicTitle": "눈물참기", "singer": "QWER", "imgUrl": ""},
    {"musicTitle": "TOO BAD", "singer": "G-DRAGON feat. Anderson .Paak", "imgUrl": ""},
    {"musicTitle": "MY LOVE(2025)", "singer": "이예은, 아샤트리, 전건호", "imgUrl": ""},
    {"musicTitle": "STYLE", "singer": "Hearts2Hearts", "imgUrl": ""},
    {"musicTitle": "LOVE WINS ALL", "singer": "아이유", "imgUrl": ""},
    {"musicTitle": "다정히 내 이름을 부르면", "singer": "경서예지, 전건호", "imgUrl": ""},
    {"musicTitle": "봄날", "singer": "방탄소년단", "imgUrl": ""},
    {"musicTitle": "헤어지자 말해요", "singer": "박재정", "imgUrl": ""},
    {"musicTitle": "모래 알갱이", "singer": "임영웅", "imgUrl": ""},
    {"musicTitle": "Ditto", "singer": "NewJeans", "imgUrl": ""},
    {"musicTitle": "사랑은 늘 도망가", "singer": "임영웅", "imgUrl": ""},
    {"musicTitle": "Super Shy", "singer": "NewJeans", "imgUrl": ""},
    {"musicTitle": "꽃", "singer": "지수 (JISOO)", "imgUrl": ""},
    {"musicTitle": "Still With You", "singer": "정국 (Jungkook)", "imgUrl": ""},
    {"musicTitle": "Smoke", "singer": "다이나믹듀오, 릴러말즈", "imgUrl": ""},
    {"musicTitle": "LOVE DIVE", "singer": "IVE", "imgUrl": ""},
    {"musicTitle": "Antifreeze", "singer": "AKMU (악뮤)", "imgUrl": ""},
    {"musicTitle": "ASAP", "singer": "STAYC", "imgUrl": ""},
    {"musicTitle": "Queencard", "singer": "아이들", "imgUrl": ""},
    {"musicTitle": "밤양갱", "singer": "비비", "imgUrl": ""},
    {"musicTitle": "사건의 지평선", "singer": "윤하", "imgUrl": ""},
    {"musicTitle": "Attention", "singer": "NewJeans", "imgUrl": ""},
    {"musicTitle": "OMG", "singer": "NewJeans", "imgUrl": ""},
    {"musicTitle": "UNFORGIVEN", "singer": "LE SSERAFIM", "imgUrl": ""},
    {"musicTitle": "Eve, Psyche & The Bluebeard’s wife", "singer": "LE SSERAFIM", "imgUrl": ""},
    {"musicTitle": "Cupid", "singer": "FIFTY FIFTY", "imgUrl": ""},
    {"musicTitle": "Spicy", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "Drama", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "Shut Down", "singer": "BLACKPINK", "imgUrl": ""},
    {"musicTitle": "Pink Venom", "singer": "BLACKPINK", "imgUrl": ""},
    {"musicTitle": "Forever", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "Illusion", "singer": "aespa", "imgUrl": ""},
    {"musicTitle": "I Don’t Think That I Like Her", "singer": "Charlie Puth", "imgUrl": ""},
    {"musicTitle": "As It Was", "singer": "Harry Styles", "imgUrl": ""},
    {"musicTitle": "Levitating", "singer": "Dua Lipa", "imgUrl": ""},
    {"musicTitle": "Kill Bill", "singer": "SZA", "imgUrl": ""},
    {"musicTitle": "Paint The Town Red", "singer": "Doja Cat", "imgUrl": ""},
    {"musicTitle": "Flowers", "singer": "Miley Cyrus", "imgUrl": ""},
    {"musicTitle": "abcdefu", "singer": "GAYLE", "imgUrl": ""},
    {"musicTitle": "good 4 u", "singer": "Olivia Rodrigo", "imgUrl": ""},
    {"musicTitle": "drivers license", "singer": "Olivia Rodrigo", "imgUrl": ""},
    {"musicTitle": "MONTERO", "singer": "Lil Nas X", "imgUrl": ""},
    {"musicTitle": "Industry Baby", "singer": "Lil Nas X, Jack Harlow", "imgUrl": ""},
    {"musicTitle": "Peaches", "singer": "Justin Bieber", "imgUrl": ""},
    {"musicTitle": "Ghost", "singer": "Justin Bieber", "imgUrl": ""},
    {"musicTitle": "Easy On Me", "singer": "Adele", "imgUrl": ""},
    {"musicTitle": "Shivers", "singer": "Ed Sheeran", "imgUrl": ""},
    {"musicTitle": "Bad Habits", "singer": "Ed Sheeran", "imgUrl": ""},
    {"musicTitle": "Blinding Lights", "singer": "The Weeknd", "imgUrl": ""},
    {"musicTitle": "Save Your Tears", "singer": "The Weeknd", "imgUrl": ""},
    {"musicTitle": "Take My Breath", "singer": "The Weeknd", "imgUrl": ""},
    {"musicTitle": "Anti-Hero", "singer": "Taylor Swift", "imgUrl": ""},
    {"musicTitle": "Cruel Summer", "singer": "Taylor Swift", "imgUrl": ""},
    {"musicTitle": "Lover", "singer": "Taylor Swift", "imgUrl": ""},
    {"musicTitle": "The Feels", "singer": "TWICE", "imgUrl": ""},
    {"musicTitle": "Set Me Free", "singer": "TWICE", "imgUrl": ""},
    {"musicTitle": "Butter", "singer": "BTS", "imgUrl": ""},
    {"musicTitle": "Dynamite", "singer": "BTS", "imgUrl": ""},
    {"musicTitle": "Permission to Dance", "singer": "BTS", "imgUrl": ""},
    {"musicTitle": "Yet to Come", "singer": "BTS", "imgUrl": ""},
    {"musicTitle": "LALISA", "singer": "LISA", "imgUrl": ""},
    {"musicTitle": "MONEY", "singer": "LISA", "imgUrl": ""},
    {"musicTitle": "Nxde", "singer": "아이들", "imgUrl": ""},
    {"musicTitle": "TOMBOY", "singer": "아이들", "imgUrl": ""},
    {"musicTitle": "ELEVEN", "singer": "IVE", "imgUrl": ""},
    {"musicTitle": "After LIKE", "singer": "IVE", "imgUrl": ""},
    {"musicTitle": "Strawberry Moon", "singer": "아이유", "imgUrl": ""},
    {"musicTitle": "Celebrity", "singer": "아이유", "imgUrl": ""},
    {"musicTitle": "에잇 (Eight)", "singer": "아이유 feat. SUGA", "imgUrl": ""},
    {"musicTitle": "Blueming", "singer": "아이유", "imgUrl": ""},
    {"musicTitle": "밤편지", "singer": "아이유", "imgUrl": ""},
    {"musicTitle": "사계", "singer": "태연", "imgUrl": ""},
    {"musicTitle": "그대라는 시", "singer": "태연", "imgUrl": ""}
  ]
  